### ISSUE TITLE
гарні практики

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/FreshCode#1]
https://github.com/TarasOstasha/FreshCode/blob/cf59ec9ae92f088caac135d772c035546c81b055/js-conditions-and-loops.js#L4-L5
- хоча при наявності одного операнда і дозволяється така форма без операторних дужок, але в комерційному коді вважається небезпечною, тому рекомендується повна:
```
 if(receivedVal === 10) {
   console.log("You paste correct nummer, Congrats!!!"); 
} else {
   console.log("Wrong Number! PLease enter again!"); 
}  
```

**Comment by TarasOstasha** [comment]
Дякую) Памятаю Ви говорили про це. Буду тепер з обережністю ставитись до такого ...
