### ISSUE TITLE
тип даних

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/FreshCode#10]
https://github.com/TarasOstasha/FreshCode/blob/9d66ffb6d60ee2812596d9994a73dd476b508cc7/js-objects.js#L91
- вік книги є, по суті, кількістю, + ми його можемо викоритовувати в арифметичних обчисленнях, тому його варто задавати типом `number`

**Comment by TarasOstasha** [comment]
логічно
дописав jsDoc для перевірки
/**
 * 
 * @param {string} bookAuthor 
 * @param {string} bookName 
 * @param {string} bookAge 
 * @param {string} bookPublishHouse 
 * @param {number} bookPrice 
 */
