### ISSUE TITLE
перевірка на парність

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/FreshCode#12]
https://github.com/TarasOstasha/FreshCode/blob/63f490754d6646aa96576d3c2c4792483256da67/arrays.js#L20
- це перевірка індекса чи елемента на парність?

**Comment by TarasOstasha** [comment]
Думаю я не правильно зрозумів умову
тому тут щоб перевірети індекси потрібно не copyOfRandomNumbers[i] використовувати а тільки і
    if(!(i%2)) {
        evenIndex.push(copyOfRandomNumbers[i]); // even index
    }
