### ISSUE TITLE
let і const для оголошення змінних з посилальними типами

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/FreshCode#14]
https://github.com/TarasOstasha/FreshCode/blob/63f490754d6646aa96576d3c2c4792483256da67/arrays.js#L60
- при оголошенні масиву, як і іншого посилального типу, найчастіше доцільно використовувати const, а не let. Для посилальних типів const не дасть випадково переприсвоїти цій змінній інше значення
```javascript
    const arr = [10, 20];
    arr = [30, 40, 50]; // не спрацює
``` 
але отак працюватиме
```javascript
    const arr = [10, 20];
    arr.push(30); // спрацює
``` 
Тобто const дасть **змінити**, але не дать **замінити** масив.

**Comment by TarasOstasha** [comment]
Ви 100% праві, зазвичай так і стараюсь писати. Але тут як завждти натупив
Дякую 👍
