### ISSUE TITLE
масив повних імен

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/FreshCode#15]
https://github.com/TarasOstasha/FreshCode/blob/f8809820aaa671303bb6f53966fa279b013d4f67/uers-array.js#L38
- осіб відфільтровано вірно, тільки потрібно ще отримати з результату **масив повних імен**

**Comment by TarasOstasha** [comment]
тут банально не дійшов до кінця. Думаю достатньо просто map викликати ?
const schoolAge = users.filter(item => !item.isMale && item.age >= 6 && item.age <= 18).map(user => user.firstName + ' ' + user.lastName)

**Comment by pecourses** [comment]
- yup). А ще можна згадати, що для повного імені реалізовано метод)
