### ISSUE TITLE
видалення

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/FreshCode#16]
https://github.com/TarasOstasha/FreshCode/blob/f8809820aaa671303bb6f53966fa279b013d4f67/uers-array.js#L41
- тут краще зробити за два етапи, спочатку знайти індекс, і якщо елемент з таким індексом знайдено, то видалити його. Інакше якщо елемента нема, якого шукаємо, то не робимо нічого. Проблема в тому, що якщо елемента не існує, `findIndex` поверне -1, а якщо першим параметром до `splice` потрапить ця -1, то це означає наступне:[ "Если отрицателен, указывает индекс элемента с конца."](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/splice#%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B), тобто буде видалено останній елемент.

**Comment by TarasOstasha** [comment]
думаю Ви мали на увазі ост так от? Так, не подумав я про це
  const userIndex = users.findIndex(item => item.email === 'useremail5@gmail.com');
  if(userIndex) {
    users.splice(userIndex, 1);
  }

**Comment by pecourses** [comment]
майже так, але прям так ми не виявимо відсутність знайденого елемента: if(userIndex) {...
оскільки якщо елемент не знайдено, то повернеться не undefined, а -1

**Comment by TarasOstasha** [comment]
тобто userIndex !== -1 , таку пеервірку?
