### ISSUE TITLE
описка

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/FreshCode#17]
https://github.com/TarasOstasha/FreshCode/blob/933746c2951f72f01cd2b2731b0d9c3820de33dc/js-switchcase.js#L20
- невірна назва функції. Небезпека подібних місць в коді в тому, що туди передається управління тільки за певних умов (тут коли введеш 'sunday'), і тільки тоді двіжок починає аналізувати код цього case і бачить, з його точки зору, неоголошений ідентифікатор `alertg`

**Comment by TarasOstasha** [comment]
Можете будь ласка детальніше?
Не зрозумів невірна назва функції, чи це мається на увазі alertg а повинно було бути просто alert?

**Comment by pecourses** [comment]
Так, має бути alert. Принаймні, якщо я вірно зрозуміла задумку автора)

**Comment by TarasOstasha** [comment]
Я зробив помилку в слові))
Дякую)
