### ISSUE TITLE
межі

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/FreshCode#2]
https://github.com/TarasOstasha/FreshCode/blob/cf59ec9ae92f088caac135d772c035546c81b055/js-conditions-and-loops.js#L25
- звернути увагу на те, яка знижка при 800 (згадати, що ми обговорювали щодо тестування коду з межами: протестувати _до_ межі, _на_ межі, _більше_ межі, тобто 250, 300, 700, 800, 850).

**Comment by TarasOstasha** [comment]
тут я думаю умову не правиьлно прочитав i замість 500 нгаписав 300. Я ще запушу зміни але думаю повинно було бути так?

if(orderAmount <= 500) - менше 500
else if(orderAmount > 500 && orderAmount <= 800) - Знижка 3% надається, якщо сума покупки більша за 500 грн.
else if(orderAmount > 800) - знижка 5% - якщо сума покупки більша за 800 грн

**Comment by pecourses** [comment]
Все вірно) Останню умову можна не перевіряти, вона і так виконуватиметься, якщо інші не тру.
