### ISSUE TITLE
затінене тло

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/FreshCode#30]
https://github.com/TarasOstasha/FreshCode/blob/28dea6979bfdfb960cbe38182c0715104094a17e/js-dom-2.js#L69
- щоб затінити тло без пощішнів, можна використати наступний прийом: виставити 2 зображення на тло, перше буде прозорим портібного відтінку, друге безпосередньо зображення. Єдине, оскільки зображення тла не можна задавати просто кольором, для вурхнього прохорого шару довоидться використати графієнт, який є опустимим для backgroundImage:
```javascript
newsInfoEl.style.backgroundImage = `linear-gradient(rgba(255,255,255,0.5),rgba(255,255,255,0.5)), url(${headerBgSrc})`;
```

**Comment by TarasOstasha** [comment]
fixed
