### ISSUE TITLE
нескінченний перерендер

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/FreshCode#46]
https://github.com/TarasOstasha/FreshCode/blob/54d09cad666301b4a7d2b90266c39aa72ccfc899/user-list/src/components/SignUpForm/index.jsx#L21-L28
- в коді ефекту встановлюється нове значення passwordIdentity, а оскільки воно в списку залежностей даного хука, то далі він знову виконується і далі по колу. Тому, якщо ми казали, що якщо якесь значення використовується в ефекті, то його ж дописати в список залежностей, то тут навпаки, якщо функція для якогось значення використовується, тоді значення в залежностях непотрібне

**Comment by TarasOstasha** [comment]
Так думаю я тут не зрозумів. малось на уавзі passwordIdentity видалити з масива обновл залежностей? Тобто залишити лише [password, confirmPassword] ?
І ще одне, де checkbox, я спочатку ініціалізую хук useStete. Наприклад checkbox agreement. const [agreement, setAgreement] = useState(false); Логічно що на початок я задаю йому стан false; і потім функція 
  function handleAgreement({ target: { checked } }) {
    console.log(checked) // при нажиманні я отримую true або false
    setAgreement(checked);
    console.log(agreement); // а от тут чомусь false якщо checked = true. Чому воно так працює? Чи я щось неправильно зробив?
  }

**Comment by pecourses** [comment]
- "Так думаю я тут не зрозумів. малось на уавзі passwordIdentity видалити з масива обновл залежностей? Тобто залишити лише [password, confirmPassword] ?" - так, все вірно, тепер не буде нескінченного перерендера. По-перше, це значення не використовується в ефекті (його значення не "читається", тільки "пишеться"), по-друге, можна пояснити це собі просто логікою, що перевірка співпадіння паролей може відбуватися в двох випадках: коли вписуєш (змінюєш) або просто пароль, або його підтвердження, тому саме ці 2 значення логічно вкладаються в масив залежностей.

- Щодо `setAgreement` - то всі `set...` - асинхронні (це ніби запит реакту "зроби це, коли зможеш"), тому спочатку виконується весь синхронний код (обидва консолелоги), а потім вже зміна параметра.
