### ISSUE TITLE
оптимізація

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/FreshCode#6]
https://github.com/TarasOstasha/FreshCode/blob/cf59ec9ae92f088caac135d772c035546c81b055/js-conditions-and-loops.js#L60
- заповнення циклу варто залишити в циклі, а ось редьюс нема сенсу запускати 100 раз, якщо нам потрібна результуюча суми, буде ефективніше і логічніше винести за цикл

**Comment by TarasOstasha** [comment]
++++
